manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: jborkowski
      url-base: https://github.com/jborkowski
  projects:
    - name: zmk
      remote: jborkowski
      revision: mouse-ftc
      import: app/west.yml
    - name: zmk
      remote: petejohanson
      revision: core/zephyr-3.4-update
      import: app/west.yml
  self:
    path: config
